# github Alacritty Colors

# Default colors
[colors.primary]
# background = '#0d1117'
background = '#000000'
foreground = '#b3b1ad'

# Normal colors
[colors.normal]
black   = '#484f58'
red     = '#ff7b72'
green   = '#81b29a'
yellow  = '#dbc074'
blue    = '#7fa1bd'
magenta = '#bc8cff'
cyan    = '#84aee4'
white   = '#b1bac4'

# blue    = '#58a6ff'
# cyan    = '#39c5cf'
# cyan    = '#58a6ff'
# green   = '#3fb950'
# yellow  = '#d29922'

# Bright colors
[colors.bright]
black   = '#6e7681'
red     = '#ffa198'
green   = '#8ebaa4'
yellow  = '#e3b341'
blue    = '#79c0ff'
magenta = '#d2a8ff'
cyan    = '#56d4dd'
white   = '#f0f6fc'

# green   = '#56d364'
# blue    = '#81a2be'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'
