# nvimlight Colors

# Default colors
[colors.primary]
foreground = '#0a0b10'
background = '#e0e2ea'

# Normal colors
[colors.normal]

blue    = "#2876cf"
cyan    = "#19a5af"
green   = "#269364"
magenta = "#af73aa"
red     = "#9e3039"
yellow  = "#54482c"
black   = '#1c1d23'
white   = '#9b9ea4'

# Bright colors
[colors.bright]

blue    = "#9fd8ff"
cyan    = "#83efef"
green   = "#aaedb7"
magenta = "#ffc3fa"
red     = "#ffbcb5"
yellow  = "#f4d88c"
black = "#9b9ea4"

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'
