[manager]
show_hidden = true
ratio = [1, 3, 4]

[opener]
open = [
    { run = 'alacritty --working-directory "$0"', orphan = true, desc = "Alacritty"},
]

edit = [
    { run = 'nvim "$@"', block = true, desc = "Edit" },
    { run = 'sudoedit "$0"', block = true, desc = "Sudo edit"}, 
]

reveal = []



